version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: pgrs_admin
      POSTGRES_PASSWORD: pgrs_password
      POSTGRES_DB: pgrs_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  app:
    # image: python:latest
    build: ./app
    container_name: python_app
    command: python /app/main.py
    volumes:
      - ./app:/app
      - ./data:/data
      - ./outputs:/outputs
    environment:
      DB_HOST: postgres_db
      # DATABASE_URL: postgres://pgrs_admin:pgrs_password@db:5432/pgrs_db
    depends_on:
      - postgres_db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
